### ISSUE TITLE
unmaskedVar to number? 

### ISSUE THREAD

**Issue by spencercap** [titou10titou10/v-mask#1]
firstly thank you thank you Denis 🙏🏼 a much needed lib now that vuetify 2.0 dropped the `mask` directive. 

wondering if there's a way to specify the type of `unmaskedVar` without setting a watcher and parsing the int/float from that. perhaps something similar to `v-model.number` or an additional field in the `v-mask` object?

**Comment by titou10titou10** [comment]
Done
You can set it with either "v-mask.number" or with the "number" attribute

**Comment by spencercap** [comment]
thanks @titou10titou10 !
