### ISSUE TITLE
A field required with Vuelidate that also has a mask gets highlighted immediately.

### ISSUE THREAD

**Issue by ghost** [titou10titou10/v-mask#2]
After upgrading to Vuetify 2 and using your v-mask to replace the old mask I noticed an issue. We use Vuelidate for form validation and when a field has both a mask and is required it gets highlighted in red immediately.

Any help would be greatly appreciated.

---

~~Demo repo: [v-mask-required](https://github.com/vuoriliikaluoma/v-mask-required)~~ _(deleted)_

The demo shows a comparison between 4 types of required fields. Note how only the Vuelidate required and masked field is prematurely highlighted.

---

Here's my shot in the dark at what the problem might be.
I'm thinking the field is being _touched_ by the directive unnecessarily.
Maybe a simple fix could be something like this:
```js
if (inputValue !== maskedValue) {
  inputValue = maskedValue;
}
```
After all there shouldn't be a need to touch the value of the input if it hasn't changed.

**Comment by titou10titou10** [comment]
Done (v1.0.5)
Thanks for reporting and for your test repository!
