### ISSUE TITLE
[Documentation] Tokens

### ISSUE THREAD

**Issue by pumpkinlink** [titou10titou10/v-mask#3]
Documentation says `tokens` should be an array of objects, but first of all the example on the README has an incorrect syntax (unclosed curly bracket): `tokens="[{ 'Y': {pattern: /[0-9]/ }]"`.

I tried the following on my component: 
``` html
<v-text-field
  v-mask="{
    mask: 'NNNNNNN',
    unmaskedVar: 'plate',
    tokens: [{
      N: {
        pattern: /[0-9a-zA-Z]/,
        transform: v => v.toLocaleUpperCase()
      }
    }]
  }"
/>
```
But all it did was keep the string 'NNNNNNN' typed on my text field. Then I removed the square brackets as follows and it worked as intended:
``` html
<v-text-field
  v-mask="{
    mask: 'NNNNNNN',
    unmaskedVar: 'plate',
    tokens: {
      N: {
        pattern: /[0-9a-zA-Z]/,
        transform: v => v.toLocaleUpperCase()
      }
    }
  }"
/>
```

**Comment by titou10titou10** [comment]
Thanks for reporting.     
I commited the change but did not build another version just for that, so the readme on the npm site is not up to date, it will be on next release
